project:
  type: website
  output-dir: docs

website:
  title: "personal_webpage"
  navbar:
    left:
      - href: docs/index.html
        text: Home
      - href: docs/Current_Research.html
        text: Current Research
      - href: docs/Resume.html
        text: Resume
      - href: docs/Projects_Publications
        text: Projects + Publications

format:
  html:
    theme:
      - darkly
      - brand
    css: styles.css
    toc: true

editor: visual

