project:
  type: website
  output-dir: docs

website:
  title: "personal_webpage"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Current_Research.qmd
        text: Current Research
      - href: Future_Work.qmd
        text: Future Work

format:
  html:
    theme:
      - darkly
      - brand
    css: styles.css
    toc: true

editor: visual

