---
title: "Projects_Publications"
---

### Current Research Projects

**Snow Density Variability in Lodgepole Pine (*Pinus contorta*) Forests**

-   Study focus: how snow distribution varies within forested stands relating to forest management

-   Location: montane watersheds in northern Colorado

-   Methods: field snow measurements, forest metrics, and data analysis

-   Relevance: implications for water supply and forest management under climate change

### Ongoing & Past Projects

**Human Scent Movement in Avalanche Debris for Search and Rescue Dogs**

-   Evaluate how carbon dioxide (CO2) moves within recent avalanche sites as a proxy for human scent

-   Focus on *in situ* data collection in southcentral Alaska

### Publications

*to come*

### Conference Presentations & Posters

-   Presentation at Joint Western and Eastern Snow Conference (ESC/WSC) in Denver, Colorado, May 2026

-   Presentation at Hydrology Days at Colorado State University in Fort Collins, Colorado, April 2026

-   Presentation at the Southcentral Alaska Avalanche Workshop (SAAW) in Anchorage, Alaska, November 2016

-   Presentation at the International Snow Science Workshop (ISSW) in Breckenridge, Colorado, October 2016
